### PR TITLE
Make mandatendb fastboot compatible 

### PR DESCRIPTION
**Pull request by aatauil**

### CODE REVIEW

**Comment by aatauil** [comment]
- ember-browser-update is not fastboot compatible and makes app unusable with fastboot
- fastboot might break the way rdfa notation behaves

**Comment by Windvis** [comment]
I created a [PR for ember-browser-update](https://github.com/erikap/ember-browser-update/pull/1) which makes it FastBoot compatible.

**Comment by Windvis** [comment]
The latest changes should make everything FastBoot compatible. I also added annotations to the mandaten-table. It's a bit verbose after dropping the rdfa modifier though. Maybe a new component which does the same can be added as a first DX improvement?

**Comment by Windvis** [comment]
One thing I noticed is that the loading state is triggered when the app boots which looks a little weird:

FastBoot rendered HTML -> loading screen -> Ember rendered HTML (which looks exactly the same).

A way around this would be to store the query results from FastBoot into the "shoebox" and retrieve that data in the Ember app when available. Ember won't need to do the query again so it wouldn't show the loading screen. This can be done in the Adapter as well, which is a thing [that StoreFront provides](https://embermap.github.io/ember-data-storefront/docs/guides/fastboot) out of the box.

I think it might be possible to extract this mixin and convert it to something that only depends on Ember Data API's but I don't think it's worth the effort, since StoreFront does provide other value as well.

**Pull request merged**
